Numpy

Numpy Array Yapısı

In [1]:
data_list=[1,2,3]

In [3]:
data_list

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
arr=np.array(data_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
data_list2=[[10,20,30],[40,50,60],[70,80,90]]

In [8]:
arr2=np.array(data_list2)

In [9]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
arr3=np.array([1,2,3,4,5])

In [11]:
arr3

array([1, 2, 3, 4, 5])

In [12]:
arr3[0]

1

In [13]:
arr3[4]

5

In [14]:
arr2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
arr2[2,2]

90

In [16]:
arr2[1,2]

60

In [17]:
arr2[0,1]

20

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(0,100,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.zeros((2,2))#2ye 2lik matris oluştur 0 değerlerini koy

array([[0., 0.],
       [0., 0.]])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
np.linspace(0,100,5)#0-100 arasını 5 parçaya böl 

array([  0.,  25.,  50.,  75., 100.])

In [27]:
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [28]:
np.eye(6)#birim matris

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [33]:
np.random.randint(0,10)

4

In [34]:
np.random.randint(1,10,5)

array([8, 6, 1, 9, 1])

In [35]:
np.random.randint(1,10,5)

array([3, 6, 8, 3, 1])

In [37]:
np.random.rand(5)

array([0.01762633, 0.09771732, 0.42283778, 0.98932124, 0.83449539])

In [40]:
np.random.randn(5)#sıfırın etrafında - + degerler

array([ 0.5372645 ,  1.06897586, -0.03282109, -0.87477687, -0.71433333])

In [41]:
arr=np.arange(25)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
newArray=np.random.randint(1,100,10)

In [45]:
newArray

array([ 8, 51, 11, 41, 98, 43, 91, 47,  5, 67])

In [46]:
newArray.max()

98

In [47]:
newArray.min()

5

In [49]:
newArray.sum()

462

In [50]:
newArray.mean()#tüm değerlerin ortalaması

46.2

In [51]:
newArray.argmax()#max sayının olduğu index

4

In [52]:
newArray.argmin()#min sayının olduğu index

8

In [53]:
detArray=np.random.randint(1,100,25)

In [54]:
detArray

array([52,  5, 55, 35, 53, 81, 75, 14, 81, 80, 72, 97, 60, 75, 17, 16, 47,
       59, 74,  3, 92, 38, 45, 68, 46])

In [55]:
detArray=detArray.reshape(5,5)

In [56]:
detArray

array([[52,  5, 55, 35, 53],
       [81, 75, 14, 81, 80],
       [72, 97, 60, 75, 17],
       [16, 47, 59, 74,  3],
       [92, 38, 45, 68, 46]])

In [58]:
np.linalg.det(detArray)#determinantı bulmak için

-835192703.9999983

In [1]:
import numpy as np

In [2]:
arr= np.arange(1,10)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[1]

2

In [5]:
arr[3]

4

In [7]:
arr[1:5]#1 ile 5 arasındaki indexler

array([2, 3, 4, 5])

In [8]:
arr[:4]

array([1, 2, 3, 4])

In [10]:
arr[::2]#2 atlayarak indexler

array([1, 3, 5, 7, 9])

In [11]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[:3]

array([1, 2, 3])

In [13]:
arr[:3]=25

In [14]:
arr

array([25, 25, 25,  4,  5,  6,  7,  8,  9])

In [15]:
arr=np.arange(1,10)

In [16]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr2=arr

In [18]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2[:3]=100

In [20]:
arr2

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [21]:
arr

array([100, 100, 100,   4,   5,   6,   7,   8,   9])

In [23]:
arr=np.arange(1,10)

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr2=arr.copy()

In [28]:
arr2[:3]=24

In [29]:
arr2

array([24, 24, 24,  4,  5,  6,  7,  8,  9])

In [30]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
newArray=np.arange(1,21)

In [32]:
newArray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [34]:
newArray=newArray.reshape(5,4)

In [35]:
newArray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [36]:
newArray[0,0]

1

In [38]:
newArray[:,:2]#satırların hepsini al sütunlarda ilk 2 elemanı

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [39]:
newArray[:3,:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [40]:
newArray[:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
newArray[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
#array filtreleme
arr=np.arange(1,11)

In [43]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
#üçten büyük değerleri almak için
arr>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [45]:
booleanArray=arr>3

In [47]:
arr[booleanArray]#false olanları almayacak

array([ 4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [1]:
import numpy as np

In [3]:
arr1=np.array([10,20,30,40,50,60])
arr2=np.array([2,3,4,5,6,7])

In [4]:
arr1+arr2

array([12, 23, 34, 45, 56, 67])

In [5]:
arr1-arr2

array([ 8, 17, 26, 35, 44, 53])

In [6]:
arr1*arr2

array([ 20,  60, 120, 200, 300, 420])

In [7]:
arr1

array([10, 20, 30, 40, 50, 60])

In [8]:
arr1+10

array([20, 30, 40, 50, 60, 70])

In [9]:
arr2-2

array([0, 1, 2, 3, 4, 5])

In [11]:
arr1/3

array([ 3.33333333,  6.66666667, 10.        , 13.33333333, 16.66666667,
       20.        ])

In [13]:
np.sqrt(arr1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781,
       7.74596669])